"""empty message

Revision ID: 33614ffd34cd
Revises: 
Create Date: 2023-07-27 10:01:18.263771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33614ffd34cd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('locations')
    # ### end Alembic commands ###
